[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["codec"]}
futures = "0.3.30"

anyhow = "1"